---
title: "20180809_黑龙江真实路网实验"
author: "wzy"
date: "2018年8月9日"
output: html_document
---

本实验在王佳琳建好的黑龙江高速公路真实路网的邻接矩阵基础上，尝试得到OD点的最短路径。进而运用一日的黑龙江收费数据，计算各段link的交通量。

```{r}
library(HVS)
```

```{r}
hlj_roadnet <- read.csv("D:\\data\\sx_raw\\黑龙江\\邻接矩阵.csv")
hlj_roadnet <- hlj_roadnet[,-1]
names(hlj_roadnet) <- 1:200
hlj_roadnet <- as.matrix(hlj_roadnet)
```

```{r}
station_index <- read.csv("D:\\data\\sx_raw\\黑龙江\\站对应序号.csv",stringsAsFactors=F)
station_infor <- read.csv("D:\\data\\sx_raw\\黑龙江\\站信息.csv",stringsAsFactors=F)
station_infor <- station_infor[,-1]
dim(station_infor)
```

```{r}
station <- merge(station_index,station_infor,by.x = "站名",by.y="收费站名称",all=T)
dim(station)
```


```{r}
result <- dijkstra_matrix(weight_mat = hlj_roadnet)
mileage <- result[[1]]
path <- result[[2]]
```

```{r}
outcome <- character(length = 200)
for(i in 1:200){
  outcome[i] <- hlj_station[hlj_station$序号==i,"SUID"]
}
```

```{r}
rownames(hlj_roadnet) <- as.numeric(outcome)
colnames(hlj_roadnet) <- as.numeric(outcome)
```

```{r}
result <- dijkstra_matrix(weight_mat = hlj_roadnet)
mileage <- result[[1]]
path <- result[[2]]
```
