---
title: "20180821_黑龙江全部数据实验"
author: "wzy"
date: "2018年8月21日"
output: html_document
---

```{r}
rm(list=ls())
```

```{r}
library(HVS)
library(magrittr)
library(knitr)
```

```{r}
load("D:/R/packages/HVS/data-raw/hlj_roadnet.RData")
load("D:/R/packages/HVS/data-raw/indextable.RData")
load("D:/R/packages/HVS/data-raw/hljsf21.RData")
load("D:/R/packages/HVS/data-raw/hljsf22.RData")
load("D:/R/packages/HVS/data-raw/hljsf23.RData")
```

```{r}
result <- dijkstra_matrix(weight_mat = hlj_roadnet)
mileage <- result[[1]]
path <- result[[2]]
```

```{r}
hljsf21$ENSEQ <- indextoseq(hljsf21$ENSTATIONINDEX)
hljsf21$EXSEQ <- indextoseq(hljsf21$EXSTATIONINDEX)
hljsf22$ENSEQ <- indextoseq(hljsf22$ENSTATIONINDEX)
hljsf22$EXSEQ <- indextoseq(hljsf22$EXSTATIONINDEX)
hljsf23$ENSEQ <- indextoseq(hljsf23$ENSTATIONINDEX)
hljsf23$EXSEQ <- indextoseq(hljsf23$EXSTATIONINDEX)
```

```{r}
hljsf21 <- hljsf21[hljsf21$ENSEQ != 0 & hljsf21$EXSEQ != 0,]
hljsf22 <- hljsf22[hljsf22$ENSEQ != 0 & hljsf22$EXSEQ != 0,]
hljsf23 <- hljsf23[hljsf23$ENSEQ != 0 & hljsf23$EXSEQ != 0,]
```

```{r}
hljsf21$path <- mapply(function(O,D) path[[O]][[D]],hljsf21$ENSEQ,hljsf21$EXSEQ)
hljsf22$path <- mapply(function(O,D) path[[O]][[D]],hljsf22$ENSEQ,hljsf22$EXSEQ)
hljsf23$path <- mapply(function(O,D) path[[O]][[D]],hljsf23$ENSEQ,hljsf23$EXSEQ)
```

```{r}
hljsf21$link <- lapply(hljsf21$path,extract_link)
hljsf22$link <- lapply(hljsf22$path,extract_link)
hljsf23$link <- lapply(hljsf23$path,extract_link)
```

```{r}
alllink <- all_link(hlj_roadnet)
```

```{r}
library(parallel)
cores <- detectCores()
cluster <- makePSOCKcluster(cores)
l <- parLapply(cluster,alllink,caculate_natureflow,hljsf21$link)
names(l) <- alllink
```

```{r}
system.time(parLapply(cluster,alllink,caculate_natureflow,hljsf21$link))
```

```{r}
d <- data.frame(traffic_volumn = simplify2array(l))
d$seqlink <- rownames(d)
d$indexlink <- seqlinktoindexlink(rownames(d))
rownames(d) <- 1:nrow(d)
d <- d[,c(3,2,1)]
write.csv(d,file="D:\\交大云同步\\实习\\11_黑龙江多源数据分析\\link计算结果\\hlj171021.csv")
```

```{r}
cores <- detectCores()
cluster <- makePSOCKcluster(cores)
l <- parLapply(cluster,alllink,caculate_natureflow,hljsf22$link)
names(l) <- alllink
```

```{r}
d <- data.frame(traffic_volumn = simplify2array(l))
d$seqlink <- rownames(d)
d$indexlink <- seqlinktoindexlink(rownames(d))
rownames(d) <- 1:nrow(d)
d <- d[,c(3,2,1)]
write.csv(d,file="D:\\交大云同步\\实习\\11_黑龙江多源数据分析\\link计算结果\\hlj171022.csv")
```

```{r}
cores <- detectCores()
cluster <- makePSOCKcluster(cores)
l <- parLapply(cluster,alllink,caculate_natureflow,hljsf23$link)
names(l) <- alllink
```

```{r}
d <- data.frame(traffic_volumn = simplify2array(l))
d$seqlink <- rownames(d)
d$indexlink <- seqlinktoindexlink(rownames(d))
rownames(d) <- 1:nrow(d)
d <- d[,c(3,2,1)]
write.csv(d,file="D:\\交大云同步\\实习\\11_黑龙江多源数据分析\\link计算结果\\hlj171023.csv")
```
