---
title: "20180821_黑龙江全部数据整理"
author: "wzy"
date: "2018年8月21日"
output: html_document
---

# 环境准备

```{r}
rm(list=ls())
```

```{r}
library(HVS)
library(magrittr)
library(knitr)
library(lubridate)
```

# 数据处理

## 哈尔滨数据

```{r}
hrb <- read.table("D:\\data\\sfsj\\黑龙江省2017年10月高速公路收费明细20171021-31（哈尔滨片区）.txt",
                  sep=",",header=F,fill=T,stringsAsFactors=F)
dim(hrb)
```

```{r}
names(hrb) <- c("ENNETINDEX","ENSTATIONINDEX","ENDATETIME","EXNETINDEX","EXSTATIONINDEX","EXDATETIME",
                "EXLANE","VLP","VC","VT","MILEAGE","AXISNUM","AXISWEIGHT","REALWEIGHT","LIMITWEIGHT",
                "OVERWEIGHTRATE","GREEN","FREETYPE","IDENTIFY","ETC","ETCOBU","PAYMENT")
```

```{r}
str(hrb)
```

删除入口网络编号和出口网络编号

```{r}
hrb$ENNETINDEX <- NULL
hrb$EXNETINDEX <- NULL
dim(hrb)
```

日期处理

```{r}
hrb$ENDATETIME <- as.POSIXct(hrb$ENDATETIME)
hrb$EXDATETIME <- as.POSIXct(hrb$EXDATETIME)
```

```{r}
unique(day(hrb$ENDATETIME))
```

```{r}
unique(year(hrb$EXDATETIME))
unique(month(hrb$EXDATETIME))
unique(day(hrb$EXDATETIME))
```

```{r}
hrb21 <- hrb[day(hrb$EXDATETIME)==21,]
hrb22 <- hrb[day(hrb$EXDATETIME)==22,]
hrb23 <- hrb[day(hrb$EXDATETIME)==23,]
```

## 鹤佳数据

```{r}
hjhg <- read.table("D:\\data\\sfsj\\黑龙江省2017年10月高速公路收费明细20171021-31（鹤佳_鹤岗）.txt",
                  sep=",",header=F,fill=T,stringsAsFactors=F)
hjhl <- read.table("D:\\data\\sfsj\\黑龙江省2017年10月高速公路收费明细20171021-31（鹤佳_鹤立）.txt",
                  sep=",",header=F,fill=T,stringsAsFactors=F)
hjjk <- read.table("D:\\data\\sfsj\\黑龙江省2017年10月高速公路收费明细20171021-31（鹤佳_江口）.txt",
                  sep=",",header=F,fill=T,stringsAsFactors=F)
dim(hjhg)
dim(hjhl)
dim(hjjk)
```

```{r}
hj <- rbind(hjhg,hjhl,hjjk)
dim(hj)
```

```{r}
names(hj) <- c("ENNETINDEX","ENSTATIONINDEX","ENDATETIME","EXNETINDEX","EXSTATIONINDEX","EXDATETIME",
                "EXLANE","VLP","VC","VT","MILEAGE","AXISNUM","AXISWEIGHT","REALWEIGHT","LIMITWEIGHT",
                "OVERWEIGHTRATE","GREEN","FREETYPE","IDENTIFY","ETC","ETCOBU","PAYMENT")
```

```{r}
hj$ENNETINDEX <- NULL
hj$EXNETINDEX <- NULL
dim(hj)
```

```{r}
hj$ENDATETIME <- as.POSIXct(hj$ENDATETIME)
hj$EXDATETIME <- as.POSIXct(hj$EXDATETIME)
```

```{r}
unique(day(hj$ENDATETIME))
```

```{r}
unique(day(hj$EXDATETIME))
```

```{r}
hj21 <- hj[day(hj$EXDATETIME)==21,]
hj22 <- hj[day(hj$EXDATETIME)==22,]
hj23 <- hj[day(hj$EXDATETIME)==23,]
```

## 齐齐哈尔数据

```{r}
qqhr <- read.table("D:\\data\\sfsj\\黑龙江省2017年10月高速公路收费明细20171021-31（齐齐哈尔片区）.txt",
                  sep=",",header=F,fill=T,stringsAsFactors=F)
dim(qqhr)
```

```{r}
names(qqhr) <- c("ENNETINDEX","ENSTATIONINDEX","ENDATETIME","EXNETINDEX","EXSTATIONINDEX","EXDATETIME",
                "EXLANE","VLP","VC","VT","MILEAGE","AXISNUM","AXISWEIGHT","REALWEIGHT","LIMITWEIGHT",
                "OVERWEIGHTRATE","GREEN","FREETYPE","IDENTIFY","ETC","ETCOBU","PAYMENT")
qqhr$ENNETINDEX <- NULL
qqhr$EXNETINDEX <- NULL
qqhr$ENDATETIME <- as.POSIXct(qqhr$ENDATETIME)
qqhr$EXDATETIME <- as.POSIXct(qqhr$EXDATETIME)
qqhr21 <- qqhr[day(qqhr$EXDATETIME)==21,]
qqhr22 <- qqhr[day(qqhr$EXDATETIME)==22,]
qqhr23 <- qqhr[day(qqhr$EXDATETIME)==23,]
```

## 数据合并

```{r}
hljsf21 <- rbind(hrb21,hj21,qqhr21)
hljsf22 <- rbind(hrb22,hj22,qqhr22)
hljsf23 <- rbind(hrb23,hj23,qqhr23)
dim(hljsf21)
dim(hljsf22)
dim(hljsf23)
```

每日数据22~23万条。

```{r}
save(hljsf21,file="D:\\R\\packages\\HVS\\data-raw\\hljsf21.RData")
save(hljsf22,file="D:\\R\\packages\\HVS\\data-raw\\hljsf22.RData")
save(hljsf23,file="D:\\R\\packages\\HVS\\data-raw\\hljsf23.RData")
```

```{r}
rm(list=ls())
```

